/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class AdminRemoveFaculty extends javax.swing.JFrame {

    /**
     * Creates new form RemoveFaculty
     */
    public AdminRemoveFaculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        RemoveButton = new javax.swing.JButton();
        FatherNameLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        PercentageLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        HQLabel = new javax.swing.JLabel();
        MobileNumberLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddressLabel = new javax.swing.JTextArea();
        EmailLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 0, 110, 90);

        jLabel2.setBackground(new java.awt.Color(0, 32, 63));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REMOVE FACULTY MEMBER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 500, 40);

        jlabel.setBackground(new java.awt.Color(0, 32, 63));
        jlabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlabel.setForeground(new java.awt.Color(187, 232, 215));
        jlabel.setText("Name :");
        jPanel1.add(jlabel);
        jlabel.setBounds(140, 200, 50, 30);

        jLabel6.setBackground(new java.awt.Color(0, 32, 63));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 232, 215));
        jLabel6.setText("Date of Birth : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 360, 100, 30);

        jLabel5.setBackground(new java.awt.Color(0, 32, 63));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 232, 215));
        jLabel5.setText("Address : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 280, 80, 30);

        jLabel3.setBackground(new java.awt.Color(0, 32, 63));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 232, 215));
        jLabel3.setText("Father's Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 240, 120, 30);

        jLabel4.setBackground(new java.awt.Color(0, 32, 63));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 232, 215));
        jLabel4.setText("Mobile no. : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 400, 90, 30);

        jLabel7.setBackground(new java.awt.Color(0, 32, 63));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(187, 232, 215));
        jLabel7.setText("Highest Qualification : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(140, 480, 160, 30);

        jLabel10.setBackground(new java.awt.Color(0, 32, 63));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 232, 215));
        jLabel10.setText("Percentage : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(140, 520, 85, 30);

        jLabel8.setBackground(new java.awt.Color(0, 32, 63));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(187, 232, 215));
        jLabel8.setText("Gender : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 560, 85, 30);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(410, 620, 150, 40);

        SearchButton.setBackground(new java.awt.Color(0, 32, 63));
        SearchButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(187, 232, 215));
        SearchButton.setText("SEARCH");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton);
        SearchButton.setBounds(450, 115, 150, 40);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(187, 232, 215));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Staff ID:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(60, 115, 80, 40);

        SearchField.setBackground(new java.awt.Color(187, 232, 215));
        SearchField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        SearchField.setForeground(new java.awt.Color(0, 32, 63));
        SearchField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SearchField.setBorder(null);
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(SearchField);
        SearchField.setBounds(160, 115, 240, 40);

        RemoveButton.setBackground(new java.awt.Color(0, 32, 63));
        RemoveButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RemoveButton.setForeground(new java.awt.Color(187, 232, 215));
        RemoveButton.setText("REMOVE");
        RemoveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RemoveButton);
        RemoveButton.setBounds(130, 620, 150, 40);

        FatherNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FatherNameLabel.setForeground(new java.awt.Color(187, 232, 215));
        FatherNameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(FatherNameLabel);
        FatherNameLabel.setBounds(350, 240, 240, 30);

        NameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(NameLabel);
        NameLabel.setBounds(350, 200, 240, 30);

        DOBLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        DOBLabel.setForeground(new java.awt.Color(187, 232, 215));
        DOBLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(DOBLabel);
        DOBLabel.setBounds(350, 360, 240, 30);

        PercentageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PercentageLabel.setForeground(new java.awt.Color(187, 232, 215));
        PercentageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(PercentageLabel);
        PercentageLabel.setBounds(350, 520, 240, 30);

        GenderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(187, 232, 215));
        GenderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(GenderLabel);
        GenderLabel.setBounds(350, 560, 240, 30);

        HQLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        HQLabel.setForeground(new java.awt.Color(187, 232, 215));
        HQLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(HQLabel);
        HQLabel.setBounds(350, 480, 240, 30);

        MobileNumberLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MobileNumberLabel.setForeground(new java.awt.Color(187, 232, 215));
        MobileNumberLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(MobileNumberLabel);
        MobileNumberLabel.setBounds(350, 400, 240, 30);

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(226, 70));

        AddressLabel.setEditable(false);
        AddressLabel.setBackground(new java.awt.Color(0, 32, 63));
        AddressLabel.setColumns(20);
        AddressLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(187, 232, 215));
        AddressLabel.setRows(5);
        AddressLabel.setBorder(null);
        AddressLabel.setPreferredSize(new java.awt.Dimension(240, 70));
        jScrollPane2.setViewportView(AddressLabel);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(350, 280, 240, 70);

        EmailLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(187, 232, 215));
        EmailLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(EmailLabel);
        EmailLabel.setBounds(350, 440, 240, 30);

        jLabel9.setBackground(new java.awt.Color(0, 32, 63));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(187, 232, 215));
        jLabel9.setText("Email : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 440, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        new AdminMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if(SearchField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Staff ID First!");
        }
        else{            
            try{                
                Connection connection;
                ResultSet rs;
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("SELECT `name`, `mobile_number`, `father_name`, `highest_qualification`, `gender`, `email`, `percentage`, `address`, DATE_FORMAT(dob,\"%M %d %Y\")as dob FROM `faculty` WHERE faculty_id="+SearchField.getText().trim());
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(null, "Invalid Staff ID");
                }
                else{
                    NameLabel.setText(rs.getString("name"));
                    FatherNameLabel.setText(rs.getString("father_name"));
                    MobileNumberLabel.setText(rs.getString("mobile_number"));
                    HQLabel.setText(rs.getString("highest_qualification"));
                    EmailLabel.setText(rs.getString("email"));
                    GenderLabel.setText(rs.getString("gender"));
                    AddressLabel.setText(rs.getString("address"));
                    PercentageLabel.setText(rs.getString("percentage"));
                    DOBLabel.setText(rs.getString("dob"));
                }
                rs.close();
                connection.close();
                statement.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        if(SearchField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "First search the book!");
        }
        else{
            Connection connection;
            PreparedStatement preparedStatement, preparedStatement1;
            try{
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
                preparedStatement = connection.prepareStatement("DELETE FROM `faculty` WHERE faculty_id = "+SearchField.getText().trim());
                preparedStatement1 = connection.prepareStatement("DELETE FROM `accounts` WHERE id = ? and account_type = ?");
                preparedStatement1.setInt(1,Integer.parseInt(SearchField.getText().trim()));
                preparedStatement1.setString(2,"faculty");
                int len, len1;
                len = 0;
                len1 = 0;
                len = preparedStatement.executeUpdate();
                len1 = preparedStatement1.executeUpdate();
                if(len>0 && len1>0){
                    JOptionPane.showMessageDialog(null,"Faculty member Deleted !");
                }
                connection.close();
                preparedStatement.close();
                dispose();
                new AdminRemoveFaculty().setVisible(true);
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRemoveFaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FatherNameLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel HQLabel;
    private javax.swing.JLabel MobileNumberLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PercentageLabel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel;
    // End of variables declaration//GEN-END:variables
}
