/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author K1LL3R
 */
public class AdminViewStudentDetail extends javax.swing.JFrame {

    /**
     * Creates new form AdminTeacherSchedule
     */
    public AdminViewStudentDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BackButton1 = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        FatherNameLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        CourseLabel = new javax.swing.JLabel();
        SessionLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        MobileNumberLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddressLabel = new javax.swing.JTextArea();
        EmailLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 32, 63));
        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(590, 0, 110, 90);

        jLabel11.setBackground(new java.awt.Color(0, 32, 63));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(187, 232, 215));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("STUDENT DETAILS");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 40, 500, 40);

        jlabel1.setBackground(new java.awt.Color(0, 32, 63));
        jlabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(187, 232, 215));
        jlabel1.setText("Name :");
        jPanel2.add(jlabel1);
        jlabel1.setBounds(140, 200, 50, 30);

        jLabel12.setBackground(new java.awt.Color(0, 32, 63));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(187, 232, 215));
        jLabel12.setText("Date of Birth : ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(140, 360, 100, 30);

        jLabel13.setBackground(new java.awt.Color(0, 32, 63));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(187, 232, 215));
        jLabel13.setText("Address : ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(140, 280, 80, 30);

        jLabel14.setBackground(new java.awt.Color(0, 32, 63));
        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(187, 232, 215));
        jLabel14.setText("Father's Name :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(140, 240, 120, 30);

        jLabel15.setBackground(new java.awt.Color(0, 32, 63));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(187, 232, 215));
        jLabel15.setText("Mobile no. : ");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(140, 400, 90, 30);

        jLabel16.setBackground(new java.awt.Color(0, 32, 63));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(187, 232, 215));
        jLabel16.setText("Gender :");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(140, 480, 160, 30);

        jLabel17.setBackground(new java.awt.Color(0, 32, 63));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(187, 232, 215));
        jLabel17.setText("Cousre :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(140, 520, 85, 30);

        jLabel18.setBackground(new java.awt.Color(0, 32, 63));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(187, 232, 215));
        jLabel18.setText("Session :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(140, 560, 85, 30);

        BackButton1.setBackground(new java.awt.Color(0, 32, 63));
        BackButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton1.setForeground(new java.awt.Color(187, 232, 215));
        BackButton1.setText("BACK");
        BackButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton1);
        BackButton1.setBounds(170, 620, 350, 50);

        SearchButton.setBackground(new java.awt.Color(0, 32, 63));
        SearchButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(187, 232, 215));
        SearchButton.setText("SEARCH");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SearchButton);
        SearchButton.setBounds(450, 115, 150, 40);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(187, 232, 215));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Student ID:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(30, 115, 110, 40);

        SearchField.setBackground(new java.awt.Color(187, 232, 215));
        SearchField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        SearchField.setForeground(new java.awt.Color(0, 32, 63));
        SearchField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SearchField.setBorder(null);
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        jPanel2.add(SearchField);
        SearchField.setBounds(160, 115, 240, 40);

        FatherNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FatherNameLabel.setForeground(new java.awt.Color(187, 232, 215));
        FatherNameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(FatherNameLabel);
        FatherNameLabel.setBounds(350, 240, 240, 30);

        NameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(NameLabel);
        NameLabel.setBounds(350, 200, 240, 30);

        DOBLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        DOBLabel.setForeground(new java.awt.Color(187, 232, 215));
        DOBLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(DOBLabel);
        DOBLabel.setBounds(350, 360, 240, 30);

        CourseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        CourseLabel.setForeground(new java.awt.Color(187, 232, 215));
        CourseLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(CourseLabel);
        CourseLabel.setBounds(350, 520, 240, 30);

        SessionLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SessionLabel.setForeground(new java.awt.Color(187, 232, 215));
        SessionLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(SessionLabel);
        SessionLabel.setBounds(350, 560, 240, 30);

        GenderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(187, 232, 215));
        GenderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(GenderLabel);
        GenderLabel.setBounds(350, 480, 240, 30);

        MobileNumberLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MobileNumberLabel.setForeground(new java.awt.Color(187, 232, 215));
        MobileNumberLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(MobileNumberLabel);
        MobileNumberLabel.setBounds(350, 400, 240, 30);

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(226, 70));

        AddressLabel.setEditable(false);
        AddressLabel.setBackground(new java.awt.Color(0, 32, 63));
        AddressLabel.setColumns(20);
        AddressLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(187, 232, 215));
        AddressLabel.setRows(5);
        AddressLabel.setBorder(null);
        AddressLabel.setPreferredSize(new java.awt.Dimension(240, 70));
        jScrollPane2.setViewportView(AddressLabel);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(350, 280, 240, 70);

        EmailLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(187, 232, 215));
        EmailLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel2.add(EmailLabel);
        EmailLabel.setBounds(350, 440, 240, 30);

        jLabel20.setBackground(new java.awt.Color(0, 32, 63));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(187, 232, 215));
        jLabel20.setText("Email : ");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(140, 440, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void BackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton1ActionPerformed
        dispose();
        new AdminMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButton1ActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if(SearchField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Student ID First!");
        }
        else{
            try{
                Connection connection;
                ResultSet rs;
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("SELECT `name`, `mobile_number`, `father_name`, `course`, `gender`, `email`, DATE_FORMAT(session_start,\"%Y\")as `session_start`, DATE_FORMAT(session_end,\"%Y\")as `session_end`, `address`, DATE_FORMAT(dob,\"%M %d %Y\")as dob FROM `student` WHERE student_id="+SearchField.getText().trim());
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(null, "Invalid Staff ID");
                }
                else{
                    NameLabel.setText(rs.getString("name"));
                    FatherNameLabel.setText(rs.getString("father_name"));
                    MobileNumberLabel.setText(rs.getString("mobile_number"));
                    GenderLabel.setText(rs.getString("gender"));
                    EmailLabel.setText(rs.getString("email"));
                    SessionLabel.setText(rs.getString("session_start")+"-"+rs.getString("session_end"));
                    AddressLabel.setText(rs.getString("address"));
                    CourseLabel.setText(rs.getString("course"));
                    DOBLabel.setText(rs.getString("dob"));
                }
                rs.close();
                connection.close();
                statement.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewStudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewStudentDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BackButton1;
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FatherNameLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel MobileNumberLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel SessionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    // End of variables declaration//GEN-END:variables
}
