/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class AdminViewProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewProfile
     */
    public AdminViewProfile() {
        initComponents();
        try{
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
            PreparedStatement preparedStatement = connection.prepareStatement("SELECT `name`, `mobile_number`, `email`, `father_name`, `gender`, `address`, DATE_FORMAT(dob,\"%M %d %Y\")as dob FROM `admin` WHERE admin_id = ?");
            preparedStatement.setInt(1,UserID.UserID);
            ResultSet rs = preparedStatement.executeQuery();
            if(rs.next()){
                NameLabel.setText(rs.getString("name"));
                MobileNumberLabel.setText(rs.getString("mobile_number"));
                EmailLabel.setText(rs.getString("email"));
                FatherNameLabel.setText(rs.getString("father_name"));
                GenderLabel.setText(rs.getString("gender"));
                AddressLabel.setText(rs.getString("address"));
                DOBLabel.setText(rs.getString("dob"));
            }
            else{
                JOptionPane.showMessageDialog(null,"Error !");
            }
            rs.close();
            connection.close();
            preparedStatement.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MobileNumberLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        GenderLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        FatherNameLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddressLabel = new javax.swing.JTextArea();
        ChangePasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 0, 110, 90);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("VIEW PROFILE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 20, 260, 40);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 232, 215));
        jLabel3.setText("Email ID                            -");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 450, 190, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 232, 215));
        jLabel4.setText("Date of Birth                    -");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 200, 190, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 232, 215));
        jLabel5.setText("Gender                              -");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 250, 190, 30);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 232, 215));
        jLabel6.setText("Address                             -");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 300, 190, 30);

        MobileNumberLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MobileNumberLabel.setForeground(new java.awt.Color(187, 232, 215));
        MobileNumberLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(MobileNumberLabel);
        MobileNumberLabel.setBounds(300, 400, 240, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 232, 215));
        jLabel10.setText("Mobile Number                  -");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 400, 190, 30);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(450, 520, 120, 50);

        UpdateButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateButton.setText("UPDATE");
        UpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton);
        UpdateButton.setBounds(100, 520, 120, 50);

        GenderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(187, 232, 215));
        GenderLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(GenderLabel);
        GenderLabel.setBounds(300, 250, 240, 30);

        DOBLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        DOBLabel.setForeground(new java.awt.Color(187, 232, 215));
        DOBLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(DOBLabel);
        DOBLabel.setBounds(300, 200, 240, 30);

        FatherNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FatherNameLabel.setForeground(new java.awt.Color(187, 232, 215));
        FatherNameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(FatherNameLabel);
        FatherNameLabel.setBounds(300, 150, 240, 30);

        NameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(NameLabel);
        NameLabel.setBounds(300, 100, 240, 30);

        EmailLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(187, 232, 215));
        EmailLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(EmailLabel);
        EmailLabel.setBounds(300, 450, 240, 30);

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(187, 232, 215));
        jLabel18.setText("Name                                -");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 100, 190, 30);

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(187, 232, 215));
        jLabel20.setText("Father's Name                 -");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(60, 150, 190, 30);

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        AddressLabel.setEditable(false);
        AddressLabel.setBackground(new java.awt.Color(0, 32, 63));
        AddressLabel.setColumns(20);
        AddressLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(187, 232, 215));
        AddressLabel.setRows(5);
        AddressLabel.setBorder(null);
        AddressLabel.setPreferredSize(new java.awt.Dimension(240, 80));
        jScrollPane2.setViewportView(AddressLabel);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(300, 300, 240, 80);

        ChangePasswordButton.setBackground(new java.awt.Color(0, 32, 63));
        ChangePasswordButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ChangePasswordButton.setForeground(new java.awt.Color(187, 232, 215));
        ChangePasswordButton.setText("<html><div style=\"text-align:center\">CHANGE<br>PASSWORD</div></html>");
        ChangePasswordButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ChangePasswordButton);
        ChangePasswordButton.setBounds(280, 520, 120, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        new AdminMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        dispose();
        new AdminUpdateProfile().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        dispose();
        new ChangePassword().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FatherNameLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel MobileNumberLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
