/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

/**
 *
 * @author K1LL3R
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UpdateProfileButton = new javax.swing.JButton();
        AddFacultyButton = new javax.swing.JButton();
        ViewProfileButton = new javax.swing.JButton();
        RemoveFacultyButton = new javax.swing.JButton();
        ViewFeedbackButton = new javax.swing.JButton();
        ViewAdmissionRequestButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JLabel();
        ViewStudentDetailButton = new javax.swing.JButton();
        StudentTimeTableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 144));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 0, 110, 90);

        jLabel2.setBackground(new java.awt.Color(0, 32, 63));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN MENU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 40, 290, 40);

        UpdateProfileButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateProfileButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateProfileButton.setText("Update Profile");
        UpdateProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UpdateProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateProfileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateProfileButtonMouseExited(evt);
            }
        });
        UpdateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateProfileButton);
        UpdateProfileButton.setBounds(80, 340, 200, 50);

        AddFacultyButton.setBackground(new java.awt.Color(0, 32, 63));
        AddFacultyButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddFacultyButton.setForeground(new java.awt.Color(187, 232, 215));
        AddFacultyButton.setText("Add faculty");
        AddFacultyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        AddFacultyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddFacultyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddFacultyButtonMouseExited(evt);
            }
        });
        AddFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFacultyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddFacultyButton);
        AddFacultyButton.setBounds(80, 230, 200, 50);

        ViewProfileButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewProfileButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewProfileButton.setText("View Profile");
        ViewProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ViewProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewProfileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewProfileButtonMouseExited(evt);
            }
        });
        ViewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewProfileButton);
        ViewProfileButton.setBounds(360, 120, 200, 50);

        RemoveFacultyButton.setBackground(new java.awt.Color(0, 32, 63));
        RemoveFacultyButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RemoveFacultyButton.setForeground(new java.awt.Color(187, 232, 215));
        RemoveFacultyButton.setText("Remove Faculty");
        RemoveFacultyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        RemoveFacultyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoveFacultyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoveFacultyButtonMouseExited(evt);
            }
        });
        RemoveFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFacultyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RemoveFacultyButton);
        RemoveFacultyButton.setBounds(360, 230, 200, 50);

        ViewFeedbackButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewFeedbackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewFeedbackButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewFeedbackButton.setText("View Feedbacks");
        ViewFeedbackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ViewFeedbackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewFeedbackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewFeedbackButtonMouseExited(evt);
            }
        });
        ViewFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFeedbackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewFeedbackButton);
        ViewFeedbackButton.setBounds(360, 340, 200, 50);

        ViewAdmissionRequestButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewAdmissionRequestButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewAdmissionRequestButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewAdmissionRequestButton.setText("View Admission Request");
        ViewAdmissionRequestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ViewAdmissionRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewAdmissionRequestButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewAdmissionRequestButtonMouseExited(evt);
            }
        });
        ViewAdmissionRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAdmissionRequestButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewAdmissionRequestButton);
        ViewAdmissionRequestButton.setBounds(80, 120, 200, 50);

        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logout.png"))); // NOI18N
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        jPanel1.add(LogoutButton);
        LogoutButton.setBounds(590, 510, 50, 50);

        ViewStudentDetailButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewStudentDetailButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewStudentDetailButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewStudentDetailButton.setText("View Student Details");
        ViewStudentDetailButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ViewStudentDetailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewStudentDetailButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewStudentDetailButtonMouseExited(evt);
            }
        });
        ViewStudentDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentDetailButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewStudentDetailButton);
        ViewStudentDetailButton.setBounds(360, 450, 200, 50);

        StudentTimeTableButton.setBackground(new java.awt.Color(0, 32, 63));
        StudentTimeTableButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StudentTimeTableButton.setForeground(new java.awt.Color(187, 232, 215));
        StudentTimeTableButton.setText("Student Time Table");
        StudentTimeTableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        StudentTimeTableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StudentTimeTableButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StudentTimeTableButtonMouseExited(evt);
            }
        });
        StudentTimeTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentTimeTableButtonActionPerformed(evt);
            }
        });
        jPanel1.add(StudentTimeTableButton);
        StudentTimeTableButton.setBounds(80, 450, 200, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProfileButtonActionPerformed
        dispose();
        new AdminUpdateProfile().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileButtonActionPerformed

    private void ViewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileButtonActionPerformed
        dispose();
        new AdminViewProfile().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ViewProfileButtonActionPerformed

    private void RemoveFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFacultyButtonActionPerformed
        dispose();
        new AdminRemoveFaculty().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_RemoveFacultyButtonActionPerformed

    private void ViewFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFeedbackButtonActionPerformed
        dispose();
        new AdminViewFeedback().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ViewFeedbackButtonActionPerformed

    private void ViewAdmissionRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAdmissionRequestButtonActionPerformed
        dispose();
        new AdminViewAdmissionRequest().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ViewAdmissionRequestButtonActionPerformed

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        dispose();
        new FacultyLogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void ViewStudentDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentDetailButtonActionPerformed
        dispose();
        new AdminViewStudentDetail().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ViewStudentDetailButtonActionPerformed

    private void StudentTimeTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentTimeTableButtonActionPerformed
        dispose();
        new AdminStudentTimeTable().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_StudentTimeTableButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void AddFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFacultyButtonActionPerformed
        dispose();
        new AdminAddFaculty().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AddFacultyButtonActionPerformed

    private void ViewAdmissionRequestButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAdmissionRequestButtonMouseEntered
        ViewAdmissionRequestButton.setBackground(new java.awt.Color(187,232,215));
        ViewAdmissionRequestButton.setForeground(new java.awt.Color(0,32,63));
        ViewAdmissionRequestButton.setText("View Admission Request");
        ViewAdmissionRequestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,32,63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewAdmissionRequestButtonMouseEntered

    private void ViewAdmissionRequestButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAdmissionRequestButtonMouseExited
        ViewAdmissionRequestButton.setBackground(new java.awt.Color(0,32,63));
        ViewAdmissionRequestButton.setForeground(new java.awt.Color(187,232,215));
        ViewAdmissionRequestButton.setText("View Admission Request");
        ViewAdmissionRequestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187,232,215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewAdmissionRequestButtonMouseExited

    private void ViewProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProfileButtonMouseEntered
        ViewProfileButton.setBackground(new java.awt.Color(187,232,215));
        ViewProfileButton.setForeground(new java.awt.Color(0,32,63));
        ViewProfileButton.setText("View Profile");
        ViewProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,32,63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewProfileButtonMouseEntered

    private void ViewProfileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProfileButtonMouseExited
        ViewProfileButton.setBackground(new java.awt.Color(0,32,63));
        ViewProfileButton.setForeground(new java.awt.Color(187,232,215));
        ViewProfileButton.setText("View Profile");
        ViewProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187,232,215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewProfileButtonMouseExited

    private void AddFacultyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFacultyButtonMouseEntered
        AddFacultyButton.setBackground(new java.awt.Color(187,232,215));
        AddFacultyButton.setForeground(new java.awt.Color(0,32,63));
        AddFacultyButton.setText("Add faculty");
        AddFacultyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,32,63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_AddFacultyButtonMouseEntered

    private void AddFacultyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFacultyButtonMouseExited
        AddFacultyButton.setBackground(new java.awt.Color(0,32,63));
        AddFacultyButton.setForeground(new java.awt.Color(187,232,215));
        AddFacultyButton.setText("Add faculty");
        AddFacultyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187,232,215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_AddFacultyButtonMouseExited

    private void RemoveFacultyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveFacultyButtonMouseEntered
        RemoveFacultyButton.setBackground(new java.awt.Color(187, 232, 215));
        RemoveFacultyButton.setForeground(new java.awt.Color(0, 32, 63));
        RemoveFacultyButton.setText("Remove Faculty");
        RemoveFacultyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_RemoveFacultyButtonMouseEntered

    private void RemoveFacultyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveFacultyButtonMouseExited
        RemoveFacultyButton.setBackground(new java.awt.Color(0, 32, 63));
        RemoveFacultyButton.setForeground(new java.awt.Color(187, 232, 215));
        RemoveFacultyButton.setText("Remove Faculty");
        RemoveFacultyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_RemoveFacultyButtonMouseExited

    private void UpdateProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileButtonMouseEntered
        UpdateProfileButton.setBackground(new java.awt.Color(187, 232, 215));
        UpdateProfileButton.setForeground(new java.awt.Color(0, 32, 63));
        UpdateProfileButton.setText("Update Profile");
        UpdateProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileButtonMouseEntered

    private void UpdateProfileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileButtonMouseExited
        UpdateProfileButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateProfileButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateProfileButton.setText("Update Profile");
        UpdateProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileButtonMouseExited

    private void ViewFeedbackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFeedbackButtonMouseEntered
        ViewFeedbackButton.setBackground(new java.awt.Color(187, 232, 215));
        ViewFeedbackButton.setForeground(new java.awt.Color(0, 32, 63));
        ViewFeedbackButton.setText("View Feedbacks");
        ViewFeedbackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewFeedbackButtonMouseEntered

    private void ViewFeedbackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFeedbackButtonMouseExited
        ViewFeedbackButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewFeedbackButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewFeedbackButton.setText("View Feedbacks");
        ViewFeedbackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewFeedbackButtonMouseExited

    private void StudentTimeTableButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTimeTableButtonMouseEntered
        StudentTimeTableButton.setBackground(new java.awt.Color(187, 232, 215));
        StudentTimeTableButton.setForeground(new java.awt.Color(0, 32, 63));
        StudentTimeTableButton.setText("Student Time Table");
        StudentTimeTableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_StudentTimeTableButtonMouseEntered

    private void StudentTimeTableButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTimeTableButtonMouseExited
        StudentTimeTableButton.setBackground(new java.awt.Color(0, 32, 63));
        StudentTimeTableButton.setForeground(new java.awt.Color(187, 232, 215));
        StudentTimeTableButton.setText("Student Time Table");
        StudentTimeTableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_StudentTimeTableButtonMouseExited

    private void ViewStudentDetailButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewStudentDetailButtonMouseEntered
        ViewStudentDetailButton.setBackground(new java.awt.Color(187, 232, 215));
        ViewStudentDetailButton.setForeground(new java.awt.Color(0, 32, 63));
        ViewStudentDetailButton.setText("View Student Details");
        ViewStudentDetailButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewStudentDetailButtonMouseEntered

    private void ViewStudentDetailButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewStudentDetailButtonMouseExited
        ViewStudentDetailButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewStudentDetailButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewStudentDetailButton.setText("View Student Details");
        ViewStudentDetailButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_ViewStudentDetailButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFacultyButton;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JButton RemoveFacultyButton;
    private javax.swing.JButton StudentTimeTableButton;
    private javax.swing.JButton UpdateProfileButton;
    private javax.swing.JButton ViewAdmissionRequestButton;
    private javax.swing.JButton ViewFeedbackButton;
    private javax.swing.JButton ViewProfileButton;
    private javax.swing.JButton ViewStudentDetailButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
