/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author K1LL3R
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameLabel1 = new javax.swing.JLabel();
        CurrentPasswordField = new javax.swing.JTextField();
        NameLabel2 = new javax.swing.JLabel();
        NewPasswordField = new javax.swing.JTextField();
        NameLabel3 = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 0, 110, 90);

        jLabel2.setBackground(new java.awt.Color(0, 32, 63));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 60, 380, 40);

        NameLabel1.setBackground(new java.awt.Color(0, 32, 63));
        NameLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel1.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel1.setText("Current Password    : ");
        jPanel1.add(NameLabel1);
        NameLabel1.setBounds(70, 150, 150, 30);

        CurrentPasswordField.setBackground(new java.awt.Color(187, 232, 215));
        CurrentPasswordField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        CurrentPasswordField.setForeground(new java.awt.Color(0, 32, 63));
        CurrentPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(CurrentPasswordField);
        CurrentPasswordField.setBounds(240, 150, 240, 30);

        NameLabel2.setBackground(new java.awt.Color(0, 32, 63));
        NameLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel2.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel2.setText("New Password          :");
        jPanel1.add(NameLabel2);
        NameLabel2.setBounds(70, 200, 150, 30);

        NewPasswordField.setBackground(new java.awt.Color(187, 232, 215));
        NewPasswordField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NewPasswordField.setForeground(new java.awt.Color(0, 32, 63));
        NewPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NewPasswordField);
        NewPasswordField.setBounds(240, 200, 240, 30);

        NameLabel3.setBackground(new java.awt.Color(0, 32, 63));
        NameLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel3.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel3.setText("Confirm Password    : ");
        jPanel1.add(NameLabel3);
        NameLabel3.setBounds(70, 250, 150, 30);

        ConfirmPasswordField.setBackground(new java.awt.Color(187, 232, 215));
        ConfirmPasswordField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(0, 32, 63));
        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPasswordField);
        ConfirmPasswordField.setBounds(240, 250, 240, 30);

        AddButton.setBackground(new java.awt.Color(0, 32, 63));
        AddButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AddButton.setForeground(new java.awt.Color(187, 232, 215));
        AddButton.setText("<html><div style=\"text-align:center\">CHANGE<br>PASSWORD</div></html>");
        AddButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton);
        AddButton.setBounds(100, 320, 150, 50);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(350, 320, 150, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurrentPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentPasswordFieldActionPerformed

    private void NewPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordFieldActionPerformed

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        if (CurrentPasswordField.getText().trim().isEmpty() || NewPasswordField.getText().trim().isEmpty() || ConfirmPasswordField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter all details first !");
        }
        else if(CurrentPasswordField.getText().trim().equals(NewPasswordField.getText().trim())){
            JOptionPane.showMessageDialog(null, "New and Old password can't be same !");
        }
        else if(!NewPasswordField.getText().trim().equals(ConfirmPasswordField.getText().trim())){
            JOptionPane.showMessageDialog(null, "New and Confirm password should be same !");
        }
        else {
            String query = "UPDATE `accounts` SET `password` = ? WHERE `id`= ? and `account_type`= ?";
            Connection connection;
            PreparedStatement preparedStatement;
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar", "root", "");
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, NewPasswordField.getText().trim());
                preparedStatement.setInt(2, UserID.UserID);
                preparedStatement.setString(3, UserID.AccountType);
                int len=0;
                len = preparedStatement.executeUpdate();
                if (len > 0) {
                    JOptionPane.showMessageDialog(null, "Password Changed Successfully !");
                }
                connection.close();
                preparedStatement.close();
                if(UserID.AccountType.equals("admin")){
                    dispose();
                    new AdminLogin().setVisible(true);
                }
                else if(UserID.AccountType.equals("faculty")){
                    dispose();
                    new FacultyLogin().setVisible(true);
                }
                else if(UserID.AccountType.equals("student")){
                    dispose();
                    new StudentLogin().setVisible(true);
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        if(UserID.AccountType.equals("admin")){
            dispose();
            new AdminMenu().setVisible(true);
        }
        else if(UserID.AccountType.equals("faculty")){
            dispose();
            new FacultyMenu().setVisible(true);
        }
        else if(UserID.AccountType.equals("student")){
            dispose();
            new StudentMenu().setVisible(true);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField ConfirmPasswordField;
    private javax.swing.JTextField CurrentPasswordField;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JLabel NameLabel2;
    private javax.swing.JLabel NameLabel3;
    private javax.swing.JTextField NewPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
