/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author K1LL3R
 */
public class FacultyUpdateResult extends javax.swing.JFrame {

    /**
     * Creates new form FacultyUpdateResult
     */
    public FacultyUpdateResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jlabel2 = new javax.swing.JLabel();
        PercentageLabel = new javax.swing.JLabel();
        Subject3Label = new javax.swing.JLabel();
        Subject4Label = new javax.swing.JLabel();
        Subject5Label = new javax.swing.JLabel();
        Subject6Label = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Subject2Label = new javax.swing.JLabel();
        Subject1Label = new javax.swing.JLabel();
        Subject1Field = new javax.swing.JTextField();
        Subject2Field = new javax.swing.JTextField();
        Subject3Field = new javax.swing.JTextField();
        Subject4Field = new javax.swing.JTextField();
        Subject5Field = new javax.swing.JTextField();
        Subject6Field = new javax.swing.JTextField();
        CourseLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 0, 110, 90);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("UPDATE RESULT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 30, 320, 40);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(187, 232, 215));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Student ID:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(60, 110, 110, 40);

        SearchField.setBackground(new java.awt.Color(187, 232, 215));
        SearchField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        SearchField.setForeground(new java.awt.Color(0, 32, 63));
        SearchField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        SearchField.setBorder(null);
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(SearchField);
        SearchField.setBounds(200, 110, 240, 40);

        SearchButton.setBackground(new java.awt.Color(0, 32, 63));
        SearchButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(187, 232, 215));
        SearchButton.setText("SEARCH");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton);
        SearchButton.setBounds(490, 110, 150, 40);

        jlabel2.setBackground(new java.awt.Color(0, 32, 63));
        jlabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(187, 232, 215));
        jlabel2.setText("Course :");
        jPanel1.add(jlabel2);
        jlabel2.setBounds(130, 180, 150, 30);

        PercentageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PercentageLabel.setForeground(new java.awt.Color(187, 232, 215));
        PercentageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(PercentageLabel);
        PercentageLabel.setBounds(340, 550, 240, 30);

        Subject3Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject3Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject3Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject3Label.setText("Subject Name :");
        jPanel1.add(Subject3Label);
        Subject3Label.setBounds(130, 320, 150, 30);

        Subject4Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject4Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject4Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject4Label.setText("Subject Name :");
        jPanel1.add(Subject4Label);
        Subject4Label.setBounds(130, 360, 150, 30);

        Subject5Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject5Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject5Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject5Label.setText("Subject Name :");
        jPanel1.add(Subject5Label);
        Subject5Label.setBounds(130, 400, 150, 30);

        Subject6Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject6Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject6Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject6Label.setText("Subject Name :");
        jPanel1.add(Subject6Label);
        Subject6Label.setBounds(130, 440, 150, 30);

        jLabel25.setBackground(new java.awt.Color(0, 32, 63));
        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(187, 232, 215));
        jLabel25.setText("Total :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(130, 500, 150, 30);

        jLabel26.setBackground(new java.awt.Color(0, 32, 63));
        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(187, 232, 215));
        jLabel26.setText("Percentage :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(130, 550, 150, 30);

        Subject2Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject2Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject2Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject2Label.setText("Subject Name :");
        jPanel1.add(Subject2Label);
        Subject2Label.setBounds(130, 280, 150, 30);

        Subject1Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject1Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject1Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject1Label.setText("Subject Name :");
        jPanel1.add(Subject1Label);
        Subject1Label.setBounds(130, 240, 150, 30);

        Subject1Field.setBackground(new java.awt.Color(187, 232, 215));
        Subject1Field.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject1Field.setForeground(new java.awt.Color(0, 32, 63));
        Subject1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject1FieldActionPerformed(evt);
            }
        });
        jPanel1.add(Subject1Field);
        Subject1Field.setBounds(340, 240, 240, 30);

        Subject2Field.setBackground(new java.awt.Color(187, 232, 215));
        Subject2Field.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject2Field.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(Subject2Field);
        Subject2Field.setBounds(340, 280, 240, 30);

        Subject3Field.setBackground(new java.awt.Color(187, 232, 215));
        Subject3Field.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject3Field.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(Subject3Field);
        Subject3Field.setBounds(340, 320, 240, 30);

        Subject4Field.setBackground(new java.awt.Color(187, 232, 215));
        Subject4Field.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject4Field.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(Subject4Field);
        Subject4Field.setBounds(340, 360, 240, 30);

        Subject5Field.setBackground(new java.awt.Color(187, 232, 215));
        Subject5Field.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject5Field.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(Subject5Field);
        Subject5Field.setBounds(340, 400, 240, 30);

        Subject6Field.setBackground(new java.awt.Color(187, 232, 215));
        Subject6Field.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject6Field.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(Subject6Field);
        Subject6Field.setBounds(340, 440, 240, 30);

        CourseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        CourseLabel.setForeground(new java.awt.Color(187, 232, 215));
        CourseLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(CourseLabel);
        CourseLabel.setBounds(340, 180, 240, 30);

        TotalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(187, 232, 215));
        TotalLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(TotalLabel);
        TotalLabel.setBounds(340, 500, 240, 30);

        UpdateButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateButton.setText("SAVE");
        UpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton);
        UpdateButton.setBounds(130, 600, 120, 40);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(470, 600, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if(SearchField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Student ID First!");
        }
        else{
            try{
                Connection connection;
                ResultSet rs;
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("SELECT `course`, `subject1`, `subject2`, `subject3`, `subject4`, `subject5`, `subject6` FROM `result` WHERE `student_id`="+SearchField.getText().trim());
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(null, "Invalid Student ID");
                }
                else{
                    CourseLabel.setText(rs.getString("course"));
                    Subject1Field.setText(rs.getString("subject1"));
                    Subject2Field.setText(rs.getString("subject2"));
                    Subject3Field.setText(rs.getString("subject3"));
                    Subject4Field.setText(rs.getString("subject4"));
                    Subject5Field.setText(rs.getString("subject5"));
                    Subject6Field.setText(rs.getString("subject6"));
                    TotalLabel.setText(Integer.toString(Integer.parseInt(Subject1Field.getText().trim())+Integer.parseInt(Subject2Field.getText().trim())+Integer.parseInt(Subject3Field.getText().trim())+Integer.parseInt(Subject4Field.getText().trim())+Integer.parseInt(Subject5Field.getText().trim())+Integer.parseInt(Subject6Field.getText().trim())));
                    PercentageLabel.setText(Integer.toString(Integer.parseInt(TotalLabel.getText().trim())/6));
                    if("BCA".equals(rs.getString("course"))){
                        Subject1Label.setText("MATHEMATICS :");
                        Subject2Label.setText("C PROGRAMMING :");
                        Subject3Label.setText("NETWORKING :");
                        Subject4Label.setText("DATABASE :");
                        Subject5Label.setText("STATSTICS :");
                        Subject6Label.setText("PRACTICAL :");
                    }
                }
                rs.close();
                connection.close();
                statement.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void Subject1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject1FieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        if (Subject1Field.getText().trim().isEmpty() || Subject2Field.getText().trim().isEmpty() || Subject3Field.getText().trim().isEmpty() || Subject4Field.getText().trim().isEmpty() || Subject5Field.getText().trim().isEmpty() || Subject6Field.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter all marks !");
        }
        else {
            String query = "UPDATE `result` SET `subject1`=?,`subject2`=?,`subject3`=?,`subject4`=?,`subject5`=?,`subject6`=? WHERE `student_id`=?";
            Connection connection;
            PreparedStatement preparedStatement;
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar", "root", "");
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setInt(1,Integer.parseInt(Subject1Field.getText().trim()));
                preparedStatement.setInt(2,Integer.parseInt(Subject2Field.getText().trim()));
                preparedStatement.setInt(3,Integer.parseInt(Subject3Field.getText().trim()));
                preparedStatement.setInt(4,Integer.parseInt(Subject4Field.getText().trim()));
                preparedStatement.setInt(5,Integer.parseInt(Subject5Field.getText().trim()));
                preparedStatement.setInt(6,Integer.parseInt(Subject6Field.getText().trim()));
                preparedStatement.setInt(7,Integer.parseInt(SearchField.getText().trim()));
                int len=0;
                len = preparedStatement.executeUpdate();
                if (len > 0) {
                    JOptionPane.showMessageDialog(null, "Result saved Successfully !");
                }
                connection.close();
                preparedStatement.close();
                dispose();
                new FacultyUpdateResult().setVisible(true);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        new FacultyMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyUpdateResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JLabel PercentageLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField Subject1Field;
    private javax.swing.JLabel Subject1Label;
    private javax.swing.JTextField Subject2Field;
    private javax.swing.JLabel Subject2Label;
    private javax.swing.JTextField Subject3Field;
    private javax.swing.JLabel Subject3Label;
    private javax.swing.JTextField Subject4Field;
    private javax.swing.JLabel Subject4Label;
    private javax.swing.JTextField Subject5Field;
    private javax.swing.JLabel Subject5Label;
    private javax.swing.JTextField Subject6Field;
    private javax.swing.JLabel Subject6Label;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel2;
    // End of variables declaration//GEN-END:variables
}
