/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

/**
 *
 * @author K1LL3R
 */
public class FacultyMenu extends javax.swing.JFrame {

    /**
     * Creates new form FacultyMenu
     */
    public FacultyMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UpdateResultButton = new javax.swing.JButton();
        UploadAssignmentButton = new javax.swing.JButton();
        UpdateProfileButton = new javax.swing.JButton();
        ViewStudentDetailButton = new javax.swing.JButton();
        ViewProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JLabel();
        GiveFeedbackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(383, 144));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 0, 110, 90);

        jLabel2.setBackground(new java.awt.Color(0, 32, 63));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("FACULTY MENU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 40, 290, 40);

        UpdateResultButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateResultButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateResultButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateResultButton.setText("Update Results");
        UpdateResultButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UpdateResultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateResultButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateResultButton);
        UpdateResultButton.setBounds(360, 230, 200, 50);

        UploadAssignmentButton.setBackground(new java.awt.Color(0, 32, 63));
        UploadAssignmentButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UploadAssignmentButton.setForeground(new java.awt.Color(187, 232, 215));
        UploadAssignmentButton.setText("Update Assignment Question");
        UploadAssignmentButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UploadAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadAssignmentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UploadAssignmentButton);
        UploadAssignmentButton.setBounds(80, 230, 200, 50);

        UpdateProfileButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateProfileButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateProfileButton.setText("Update Profile");
        UpdateProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UpdateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateProfileButton);
        UpdateProfileButton.setBounds(360, 120, 200, 50);

        ViewStudentDetailButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewStudentDetailButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewStudentDetailButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewStudentDetailButton.setText("View Student Details");
        ViewStudentDetailButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ViewStudentDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentDetailButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewStudentDetailButton);
        ViewStudentDetailButton.setBounds(80, 340, 200, 50);

        ViewProfileButton.setBackground(new java.awt.Color(0, 32, 63));
        ViewProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewProfileButton.setForeground(new java.awt.Color(187, 232, 215));
        ViewProfileButton.setText("View Profile");
        ViewProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ViewProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewProfileButton);
        ViewProfileButton.setBounds(80, 120, 200, 50);

        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logout.png"))); // NOI18N
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        jPanel1.add(LogoutButton);
        LogoutButton.setBounds(590, 400, 50, 50);

        GiveFeedbackButton.setBackground(new java.awt.Color(0, 32, 63));
        GiveFeedbackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        GiveFeedbackButton.setForeground(new java.awt.Color(187, 232, 215));
        GiveFeedbackButton.setText(" Give Feedback");
        GiveFeedbackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        GiveFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiveFeedbackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GiveFeedbackButton);
        GiveFeedbackButton.setBounds(360, 340, 200, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateResultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateResultButtonActionPerformed
        dispose();
        new FacultyUpdateResult().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateResultButtonActionPerformed

    private void UpdateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProfileButtonActionPerformed
        dispose();
        new FacultyUpdateProfile().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileButtonActionPerformed

    private void ViewStudentDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentDetailButtonActionPerformed
        dispose();
        new FacultyViewStudentDetail().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ViewStudentDetailButtonActionPerformed

    private void ViewProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileButtonActionPerformed
        dispose();
        new FacultyViewProfile().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ViewProfileButtonActionPerformed

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        dispose();
        new FacultyLogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void GiveFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiveFeedbackButtonActionPerformed
        dispose();
        new GiveFeedback().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_GiveFeedbackButtonActionPerformed

    private void UploadAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadAssignmentButtonActionPerformed
        dispose();
        new FacultyUploadAssignment().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UploadAssignmentButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GiveFeedbackButton;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JButton UpdateProfileButton;
    private javax.swing.JButton UpdateResultButton;
    private javax.swing.JButton UploadAssignmentButton;
    private javax.swing.JButton ViewProfileButton;
    private javax.swing.JButton ViewStudentDetailButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
