/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class GiveFeedback extends javax.swing.JFrame {

    /**
     * Creates new form GiveFeedback
     */
    public GiveFeedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FeedbackArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LikeRB = new javax.swing.JRadioButton();
        DislikeRB = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(LogoLabel);
        LogoLabel.setBounds(490, 0, 110, 100);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("FEEDBACK FORM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 30, 320, 70);

        jScrollPane1.setBorder(null);

        FeedbackArea.setBackground(new java.awt.Color(187, 232, 215));
        FeedbackArea.setColumns(20);
        FeedbackArea.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FeedbackArea.setForeground(new java.awt.Color(0, 32, 63));
        FeedbackArea.setRows(5);
        FeedbackArea.setBorder(null);
        jScrollPane1.setViewportView(FeedbackArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 220, 370, 120);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 232, 215));
        jLabel1.setText("How our software feel to you ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 150, 210, 30);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 232, 215));
        jLabel3.setText("Describe your thoughts :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 220, 137, 30);

        LikeRB.setBackground(new java.awt.Color(0, 32, 63));
        LikeRB.setForeground(new java.awt.Color(187, 232, 215));
        LikeRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LikeRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/LikeG.png"))); // NOI18N
        LikeRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LikeRBMouseClicked(evt);
            }
        });
        jPanel1.add(LikeRB);
        LikeRB.setBounds(320, 130, 60, 60);

        DislikeRB.setBackground(new java.awt.Color(0, 32, 63));
        DislikeRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DislikeRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/DislikeG.png"))); // NOI18N
        DislikeRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DislikeRBMouseClicked(evt);
            }
        });
        jPanel1.add(DislikeRB);
        DislikeRB.setBounds(460, 130, 60, 60);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setToolTipText("");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackButtonMouseExited(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(350, 370, 140, 40);

        SubmitButton.setBackground(new java.awt.Color(0, 32, 63));
        SubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(187, 232, 215));
        SubmitButton.setText("SUBMIT");
        SubmitButton.setToolTipText("");
        SubmitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseExited(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton);
        SubmitButton.setBounds(110, 370, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void BackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseEntered
        BackButton.setBackground(new java.awt.Color(187, 232, 215));
        BackButton.setForeground(new java.awt.Color(0, 32, 63));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseEntered

    private void BackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseExited
        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseExited

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        if("student".equals(UserID.AccountType)){
            dispose();
            new StudentMenu().setVisible(true);
        }
        else if("faculty".equals(UserID.AccountType)){
            dispose();
            new FacultyMenu().setVisible(true);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SubmitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseEntered
        SubmitButton.setBackground(new java.awt.Color(187, 232, 215));
        SubmitButton.setForeground(new java.awt.Color(0, 32, 63));
        SubmitButton.setText("SUBMIT");
        SubmitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 32, 63), 4));// TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonMouseEntered

    private void SubmitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseExited
        SubmitButton.setBackground(new java.awt.Color(0, 32, 63));
        SubmitButton.setForeground(new java.awt.Color(187, 232, 215));
        SubmitButton.setText("SUBMIT");
        SubmitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));// TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonMouseExited

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        if(FeedbackArea.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter all details first !");
        }
        else if(LikeRB.isSelected() || DislikeRB.isSelected()){
            try{
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
                PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO `feedback`(`feedback_type`, `description`) VALUES (?,?)");
                if(LikeRB.isSelected()){
                    preparedStatement.setString(1,"Good");
                }
                else if(DislikeRB.isSelected()){
                    preparedStatement.setString(1,"Bad");
                }
                preparedStatement.setString(2,FeedbackArea.getText().trim());
                int len = 0;
                len = preparedStatement.executeUpdate();
                if(len > 0){
                    JOptionPane.showMessageDialog(null,"Feedback Submitted !");
                }
                preparedStatement.close();
                connection.close();
                dispose();
                new GiveFeedback().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter all details first !");
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void LikeRBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LikeRBMouseClicked
        LikeRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/LikeG.png")));
        DislikeRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/DislikeB.png")));
        LikeRB.setSelected(true);
        DislikeRB.setSelected(false);
    }//GEN-LAST:event_LikeRBMouseClicked

    private void DislikeRBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DislikeRBMouseClicked
        LikeRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/LikeB.png")));
        DislikeRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/DislikeG.png")));
        LikeRB.setSelected(false);
        DislikeRB.setSelected(true);
    }//GEN-LAST:event_DislikeRBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton DislikeRB;
    private javax.swing.JTextArea FeedbackArea;
    private javax.swing.JRadioButton LikeRB;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
