/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class StudentUpdateProfile extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProfile
     */
    public StudentUpdateProfile() {
        initComponents();
        try{
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
            PreparedStatement preparedStatement = connection.prepareStatement("SELECT `name`, `mobile_number`, `email`, `father_name`, `gender`, `address`, `dob` FROM `student` WHERE student_id = ?");
            preparedStatement.setInt(1,UserID.UserID);
            ResultSet rs = preparedStatement.executeQuery();
            if(rs.next()){
                NameField.setText(rs.getString("name"));
                MobileNumberField.setText(rs.getString("mobile_number"));
                EmailField.setText(rs.getString("email"));
                FatherNameField.setText(rs.getString("father_name"));
                GenderField.setText(rs.getString("gender"));
                AddressField.setText(rs.getString("address"));
                String date = rs.getString("dob");
                int temp = 0;
                for(int i=0;i<4;i++){
                    temp = temp * 10 + Integer.parseInt(String.valueOf(date.charAt(i)));
                }
                YearCB.setSelectedItem(Integer.toString(temp));
                temp = 0;
                for(int i=5;i<7;i++){
                    temp = temp * 10 + Integer.parseInt(String.valueOf(date.charAt(i)));
                }
                MonthCB.setSelectedItem(String.format("%02d",temp));
                temp = 0;
                for(int i=8;i<10;i++){
                    temp = temp * 10 + Integer.parseInt(String.valueOf(date.charAt(i)));
                }
                DateCB.setSelectedItem(String.format("%02d",temp));
            }
            else{
                JOptionPane.showMessageDialog(null,"Error !");
            }
            rs.close();
            connection.close();
            preparedStatement.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        FatherNameField = new javax.swing.JTextField();
        GenderField = new javax.swing.JTextField();
        MobileNumberField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressField = new javax.swing.JTextArea();
        DateCB = new javax.swing.JComboBox<>();
        MonthCB = new javax.swing.JComboBox<>();
        YearCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(283, 84));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 0, 110, 90);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("UPDATE PROFILE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 20, 320, 40);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 232, 215));
        jLabel3.setText("Email ID                            -");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 450, 180, 30);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 232, 215));
        jLabel4.setText("Date of Birth                    -");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 200, 180, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 232, 215));
        jLabel5.setText("Gender                              -");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 250, 180, 30);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 232, 215));
        jLabel6.setText("Address                             -");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 300, 180, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 232, 215));
        jLabel10.setText("Mobile Number                  -");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 400, 180, 30);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(425, 510, 150, 50);

        UpdateButton.setBackground(new java.awt.Color(0, 32, 63));
        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(187, 232, 215));
        UpdateButton.setText("SAVE");
        UpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton);
        UpdateButton.setBounds(125, 510, 150, 50);

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(187, 232, 215));
        jLabel18.setText("Name                                -");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(120, 100, 180, 30);

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(187, 232, 215));
        jLabel20.setText("Father's Name                 -");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(120, 150, 180, 30);

        EmailField.setBackground(new java.awt.Color(187, 232, 215));
        EmailField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EmailField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(EmailField);
        EmailField.setBounds(320, 450, 240, 27);

        FatherNameField.setBackground(new java.awt.Color(187, 232, 215));
        FatherNameField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FatherNameField.setForeground(new java.awt.Color(0, 32, 63));
        FatherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(FatherNameField);
        FatherNameField.setBounds(320, 150, 240, 27);

        GenderField.setBackground(new java.awt.Color(187, 232, 215));
        GenderField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenderField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(GenderField);
        GenderField.setBounds(320, 250, 240, 27);

        MobileNumberField.setBackground(new java.awt.Color(187, 232, 215));
        MobileNumberField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MobileNumberField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(MobileNumberField);
        MobileNumberField.setBounds(320, 400, 240, 27);

        NameField.setBackground(new java.awt.Color(187, 232, 215));
        NameField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameField.setForeground(new java.awt.Color(0, 32, 63));
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NameField);
        NameField.setBounds(320, 100, 240, 27);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        AddressField.setBackground(new java.awt.Color(187, 232, 215));
        AddressField.setColumns(20);
        AddressField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddressField.setForeground(new java.awt.Color(0, 32, 63));
        AddressField.setRows(5);
        jScrollPane1.setViewportView(AddressField);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(320, 300, 240, 80);

        DateCB.setBackground(new java.awt.Color(187, 232, 215));
        DateCB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DateCB.setForeground(new java.awt.Color(0, 32, 63));
        DateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "01", "02", "03", "04", "05", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateCBActionPerformed(evt);
            }
        });
        jPanel1.add(DateCB);
        DateCB.setBounds(320, 200, 60, 30);

        MonthCB.setBackground(new java.awt.Color(187, 232, 215));
        MonthCB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MonthCB.setForeground(new java.awt.Color(0, 32, 63));
        MonthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(MonthCB);
        MonthCB.setBounds(400, 200, 70, 30);

        YearCB.setBackground(new java.awt.Color(187, 232, 215));
        YearCB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        YearCB.setForeground(new java.awt.Color(0, 32, 63));
        YearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel1.add(YearCB);
        YearCB.setBounds(500, 200, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        new StudentMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        if (NameField.getText().trim().isEmpty() || FatherNameField.getText().trim().isEmpty() || MobileNumberField.getText().trim().isEmpty() || EmailField.getText().trim().isEmpty() || GenderField.getText().trim().isEmpty() || AddressField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter all details first !");
        }
        else {
            String query = "UPDATE `student` SET `name`= ?,`father_name`= ?,`gender`= ?,`address`= ?,`mobile_number`= ?,`email`= ?,`dob`= ? WHERE student_id = ?";
            Connection connection;
            PreparedStatement preparedStatement;
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar", "root", "");
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, NameField.getText().trim());
                preparedStatement.setString(2, FatherNameField.getText().trim());
                preparedStatement.setString(3, GenderField.getText().trim());
                preparedStatement.setString(4, AddressField.getText().trim());
                preparedStatement.setString(5, MobileNumberField.getText().trim());
                preparedStatement.setString(6, EmailField.getText().trim());
                preparedStatement.setInt(8,UserID.UserID);
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                format.setLenient(false);
                String date = YearCB.getSelectedItem() + "-" + MonthCB.getSelectedItem() + "-" + DateCB.getSelectedItem();
                try {
                    format.parse(date);
                    preparedStatement.setString(7, date);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Invalid Date !");
                }
                int len=0;
                len = preparedStatement.executeUpdate();
                if (len > 0) {
                    JOptionPane.showMessageDialog(null, "Details updated Successfully !");
                }
                connection.close();
                preparedStatement.close();
                dispose();
                new FacultyMenu().setVisible(true);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void DateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateCBActionPerformed

    private void FatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUpdateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressField;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> DateCB;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField FatherNameField;
    private javax.swing.JTextField GenderField;
    private javax.swing.JTextField MobileNumberField;
    private javax.swing.JComboBox<String> MonthCB;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JComboBox<String> YearCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
