/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class StudentRequestForm extends javax.swing.JFrame {

    /**
     * Creates new form RequestForm
     */
    public StudentRequestForm() {
        initComponents();
        if(UserID.flag == true){
            NameField.setText(UserID.temp[1]);
            PasswordField.setText(UserID.temp[0]);
            AddressField.setText(UserID.temp[5]);
            FatherNameField.setText(UserID.temp[2]);
            MobileNumberField.setText(UserID.temp[3]);
            EmailField.setText(UserID.temp[4]);
            PercentageField.setText(UserID.temp[10]);
            String date = UserID.temp[7];
            int temp = 0;
            for(int i=0;i<4;i++){
                temp = temp * 10 + Integer.parseInt(String.valueOf(date.charAt(i)));
            }
            YearCB.setSelectedItem(Integer.toString(temp));
            temp = 0;
            for(int i=5;i<7;i++){
                temp = temp * 10 + Integer.parseInt(String.valueOf(date.charAt(i)));
            }
            MonthCB.setSelectedItem(String.format("%02d",temp));
            temp = 0;
            for(int i=8;i<10;i++){
                temp = temp * 10 + Integer.parseInt(String.valueOf(date.charAt(i)));
            }
            DateCB.setSelectedItem(String.format("%02d",temp));
            HQCB.setSelectedItem(UserID.temp[9]);
            CourseCB.setSelectedItem(UserID.temp[8]);
            if("Male".equals(UserID.temp[6])){
                MaleRB.setSelected(true);
            }
            else if("Female".equals(UserID.temp[6])){
                FemaleRB.setSelected(true);
            }
            else if("Other".equals(UserID.temp[6])){
                OtherRB.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PercentageField = new javax.swing.JTextField();
        MobileNumberField = new javax.swing.JTextField();
        FatherNameField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressField = new javax.swing.JTextArea();
        DateCB = new javax.swing.JComboBox<>();
        MonthCB = new javax.swing.JComboBox<>();
        YearCB = new javax.swing.JComboBox<>();
        HQCB = new javax.swing.JComboBox<>();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        OtherRB = new javax.swing.JRadioButton();
        CourseCB = new javax.swing.JComboBox<>();
        BackButton = new javax.swing.JButton();
        ReviewApplicationButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(283, 59));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 32, 63));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 232, 215));
        jLabel1.setText("REQUEST FORM FOR ADMISSION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 586, 50);

        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(LogoLabel);
        LogoLabel.setBounds(690, 0, 110, 90);

        NameLabel.setBackground(new java.awt.Color(0, 32, 63));
        NameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(187, 232, 215));
        NameLabel.setText("Name : ");
        jPanel1.add(NameLabel);
        NameLabel.setBounds(160, 80, 60, 30);

        jLabel3.setBackground(new java.awt.Color(0, 32, 63));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 232, 215));
        jLabel3.setText("Father's Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 320, 120, 30);

        jLabel4.setBackground(new java.awt.Color(0, 32, 63));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 232, 215));
        jLabel4.setText("Mobile no. : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 360, 90, 30);

        jLabel5.setBackground(new java.awt.Color(0, 32, 63));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(187, 232, 215));
        jLabel5.setText("Address : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 200, 80, 30);

        jLabel6.setBackground(new java.awt.Color(0, 32, 63));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(187, 232, 215));
        jLabel6.setText("Password : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 120, 100, 30);

        jLabel7.setBackground(new java.awt.Color(0, 32, 63));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(187, 232, 215));
        jLabel7.setText("Highest Qualification : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 440, 160, 30);

        jLabel8.setBackground(new java.awt.Color(0, 32, 63));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(187, 232, 215));
        jLabel8.setText("Gender : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 520, 85, 30);

        jLabel9.setBackground(new java.awt.Color(0, 32, 63));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(187, 232, 215));
        jLabel9.setText("Course : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 280, 60, 30);

        PercentageField.setBackground(new java.awt.Color(187, 232, 215));
        PercentageField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PercentageField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(PercentageField);
        PercentageField.setBounds(330, 480, 300, 30);

        MobileNumberField.setBackground(new java.awt.Color(187, 232, 215));
        MobileNumberField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        MobileNumberField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(MobileNumberField);
        MobileNumberField.setBounds(330, 360, 300, 30);

        FatherNameField.setBackground(new java.awt.Color(187, 232, 215));
        FatherNameField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        FatherNameField.setForeground(new java.awt.Color(0, 32, 63));
        FatherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(FatherNameField);
        FatherNameField.setBounds(330, 320, 300, 30);

        NameField.setBackground(new java.awt.Color(187, 232, 215));
        NameField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NameField.setForeground(new java.awt.Color(0, 32, 63));
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NameField);
        NameField.setBounds(330, 80, 300, 30);

        jLabel10.setBackground(new java.awt.Color(0, 32, 63));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 232, 215));
        jLabel10.setText("Percentage : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 480, 85, 30);

        jScrollPane1.setBackground(new java.awt.Color(187, 232, 215));
        jScrollPane1.setForeground(new java.awt.Color(0, 32, 63));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        AddressField.setBackground(new java.awt.Color(187, 232, 215));
        AddressField.setColumns(20);
        AddressField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddressField.setForeground(new java.awt.Color(0, 32, 63));
        AddressField.setRows(5);
        jScrollPane1.setViewportView(AddressField);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 200, 300, 70);

        DateCB.setBackground(new java.awt.Color(187, 232, 215));
        DateCB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        DateCB.setForeground(new java.awt.Color(0, 32, 63));
        DateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "01", "02", "03", "04", "05", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateCBActionPerformed(evt);
            }
        });
        jPanel1.add(DateCB);
        DateCB.setBounds(330, 160, 80, 30);

        MonthCB.setBackground(new java.awt.Color(187, 232, 215));
        MonthCB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MonthCB.setForeground(new java.awt.Color(0, 32, 63));
        MonthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(MonthCB);
        MonthCB.setBounds(430, 160, 100, 30);

        YearCB.setBackground(new java.awt.Color(187, 232, 215));
        YearCB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        YearCB.setForeground(new java.awt.Color(0, 32, 63));
        YearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel1.add(YearCB);
        YearCB.setBounds(550, 160, 80, 30);

        HQCB.setBackground(new java.awt.Color(187, 232, 215));
        HQCB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        HQCB.setForeground(new java.awt.Color(0, 32, 63));
        HQCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Qualification", "12th Standard", "Diploma", "Graduate", "Post Graduate", " " }));
        HQCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HQCBActionPerformed(evt);
            }
        });
        jPanel1.add(HQCB);
        HQCB.setBounds(330, 440, 300, 30);

        MaleRB.setBackground(new java.awt.Color(0, 32, 63));
        MaleRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        MaleRB.setForeground(new java.awt.Color(187, 232, 215));
        MaleRB.setText("Male");
        MaleRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaleRBMouseClicked(evt);
            }
        });
        MaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRBActionPerformed(evt);
            }
        });
        jPanel1.add(MaleRB);
        MaleRB.setBounds(330, 520, 80, 30);

        FemaleRB.setBackground(new java.awt.Color(0, 32, 63));
        FemaleRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        FemaleRB.setForeground(new java.awt.Color(187, 232, 215));
        FemaleRB.setText("Female");
        FemaleRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FemaleRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemaleRBMouseClicked(evt);
            }
        });
        jPanel1.add(FemaleRB);
        FemaleRB.setBounds(440, 520, 80, 30);

        OtherRB.setBackground(new java.awt.Color(0, 32, 63));
        OtherRB.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        OtherRB.setForeground(new java.awt.Color(187, 232, 215));
        OtherRB.setText("Others");
        OtherRB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        OtherRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OtherRBMouseClicked(evt);
            }
        });
        OtherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRBActionPerformed(evt);
            }
        });
        jPanel1.add(OtherRB);
        OtherRB.setBounds(550, 520, 80, 30);

        CourseCB.setBackground(new java.awt.Color(187, 232, 215));
        CourseCB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        CourseCB.setForeground(new java.awt.Color(0, 32, 63));
        CourseCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course", "BCA", "BBA", "B.Com.", "B.Ed.", "B.Sc.", "B.Tech." }));
        jPanel1.add(CourseCB);
        CourseCB.setBounds(330, 280, 300, 30);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(480, 580, 160, 50);

        ReviewApplicationButton.setBackground(new java.awt.Color(0, 32, 63));
        ReviewApplicationButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ReviewApplicationButton.setForeground(new java.awt.Color(187, 232, 215));
        ReviewApplicationButton.setText("Review Application");
        ReviewApplicationButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        ReviewApplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewApplicationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReviewApplicationButton);
        ReviewApplicationButton.setBounds(170, 580, 160, 50);

        jLabel11.setBackground(new java.awt.Color(0, 32, 63));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(187, 232, 215));
        jLabel11.setText("Email : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 400, 90, 30);

        EmailField.setBackground(new java.awt.Color(187, 232, 215));
        EmailField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EmailField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(EmailField);
        EmailField.setBounds(330, 400, 300, 30);

        jLabel12.setBackground(new java.awt.Color(0, 32, 63));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(187, 232, 215));
        jLabel12.setText("Date of Birth : ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 160, 100, 30);

        PasswordField.setBackground(new java.awt.Color(187, 232, 215));
        PasswordField.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 32, 63));
        jPanel1.add(PasswordField);
        PasswordField.setBounds(330, 120, 300, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateCBActionPerformed

    private void OtherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherRBActionPerformed

    private void FatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameFieldActionPerformed

    private void ReviewApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewApplicationButtonActionPerformed
        if (NameField.getText().trim().isEmpty() || EmailField.getText().trim().isEmpty() || PasswordField.getText().trim().isEmpty() || PercentageField.getText().trim().isEmpty() || FatherNameField.getText().trim().isEmpty() || AddressField.getText().trim().isEmpty() || MobileNumberField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter all details first !");
        } 
        else if(HQCB.getSelectedItem() == "Select Qualification"){
            JOptionPane.showMessageDialog(null, "Select proper Qualification !");
        }
        else if(CourseCB.getSelectedItem() == "Select Course"){
            JOptionPane.showMessageDialog(null, "Select a course !");
        }
        else if(MaleRB.isSelected() || FemaleRB.isSelected() || OtherRB.isSelected()){
            try{
                String passwordString = new String(PasswordField.getPassword());
                UserID.temp[0] = passwordString;
                UserID.temp[1] = NameField.getText().trim();
                UserID.temp[2] = FatherNameField.getText().trim();
                UserID.temp[3] = MobileNumberField.getText().trim();
                UserID.temp[4] = EmailField.getText().trim();
                UserID.temp[5] = AddressField.getText().trim();
                UserID.temp[8] = (String) CourseCB.getSelectedItem();
                UserID.temp[9] = (String) HQCB.getSelectedItem();
                UserID.temp[10] = PercentageField.getText().trim();
                if (MaleRB.isSelected()) {
                    UserID.temp[6] = "Male";
                }
                else if (FemaleRB.isSelected()) {
                    UserID.temp[6] = "Female";
                }
                else if (OtherRB.isSelected()) {
                    UserID.temp[6] = "Other";
                }
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                format.setLenient(false);
                String date = YearCB.getSelectedItem() + "-" + MonthCB.getSelectedItem() + "-" + DateCB.getSelectedItem();
                try {
                    format.parse(date);
                    UserID.temp[7] = date;
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Invalid Date !");
                }
                UserID.flag = false;
                dispose();
                new StudentViewApplication().setVisible(true);
                //for(int i=0;i<11;i++){
                //    System.out.println(UserID.temp[i]+"\n");
                //}
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a gender !");
        }
    }//GEN-LAST:event_ReviewApplicationButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        new StudentLogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void MaleRBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaleRBMouseClicked
        FemaleRB.setSelected(false);
        OtherRB.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_MaleRBMouseClicked

    private void FemaleRBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemaleRBMouseClicked
        MaleRB.setSelected(false);
        OtherRB.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_FemaleRBMouseClicked

    private void OtherRBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OtherRBMouseClicked
        MaleRB.setSelected(false);
        FemaleRB.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_OtherRBMouseClicked

    private void MaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRBActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void HQCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HQCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HQCBActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRequestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressField;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> CourseCB;
    private javax.swing.JComboBox<String> DateCB;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField FatherNameField;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JComboBox<String> HQCB;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JTextField MobileNumberField;
    private javax.swing.JComboBox<String> MonthCB;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JRadioButton OtherRB;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField PercentageField;
    private javax.swing.JButton ReviewApplicationButton;
    private javax.swing.JComboBox<String> YearCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
