/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;
import java.sql.*;
import java.util.Date;
import java.util.Calendar;
import java.text.*;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class StudentViewApplication extends javax.swing.JFrame {

    private int year;

    /**
     * Creates new form ViewApplication
     */
    public StudentViewApplication() {
        initComponents();
        year = Calendar.getInstance().get(Calendar.YEAR);
        int month = Calendar.getInstance().get(Calendar.MONTH);
        if (month>9 || month<4){
            year++;
        }
        Date date = Calendar.getInstance().getTime();  
        DateFormat dateFormat = new SimpleDateFormat("dd-MMM-YYYY");  
        String strDate = dateFormat.format(date);
        String gender = null;
        String hisher = null;
        if("Male".equals(UserID.temp[6]) || "Other".equals(UserID.temp[6])){
            gender = "son";
            hisher = "his";
        }
        else if("Female".equals(UserID.temp[6])){
            gender = "daughter";
            hisher = "her";
        }
        ApplicationArea.setText("To,\n"+
                                "The Principal,\n"+
                                "XYZ COLLEGE, Meerut\n\n\t"+
                                "Subject: Request to enroll for admission in "+UserID.temp[8]+" session "+year+"-"+(year+3)+"\n\n"+
                                "Dear Sir/madam,\n"+
                                "This is "+UserID.temp[2]+" and it is my humble request to kindly admit my "+gender+"\n"+
                                UserID.temp[1]+" in"+UserID.temp[8]+" of your institution.\n\n"+
                                "I am pleased to inform you about the overall impressive academic performance\n"+
                                "of my "+gender+" until now. After research, I found your college is undoubtedly the\n"+
                                "best in your neighbourhood and therefore it is the most obvious choice for "+hisher+" career.\n"+
                                "My child is an ambitious student, and in your college we expect to see\n"+
                                hisher+" skills grow further, especially under the guidance of talented teachers\n"+
                                "that work in your college.\n\n"+
                                "Yours truly\n"+
                                UserID.temp[2]+"\n"+
                                "Date : "+strDate+"\n\n\n"+
                                "Further Details: \n\n"+
                                "Date of Birth - "+UserID.temp[7]+"\n"+
                                "Mobile No. - "+UserID.temp[3]+"\n"+
                                "Email - "+UserID.temp[4]+"\n"+        
                                "Address - "+UserID.temp[5]+"\n"+
                                "Highest Qualification - "+UserID.temp[9]+"\n"+
                                "Percentage - "+UserID.temp[10]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ApplicationArea = new javax.swing.JTextArea();
        EditButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(383, 0));
        setPreferredSize(new java.awt.Dimension(600, 710));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 232, 215));
        jLabel1.setText("Application for Admission");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 0, 304, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 0, 110, 90);

        jScrollPane1.setToolTipText("To,\nThe Principal,\nXYZ COLLEGE, Meerut\n\n\tSubject: Request to enroll for admission in ________ session 20__-20__\n\nDear Sir/madam,\nThis is __________ and it is my humble request to kindly admit my ______ _________ in ______ of your institution.\n\nI am pleased to inform you about the overall impressive academic performance of my child until now. After research, I found your college is undoubtedly the best in your neighbourhood and therefore it is the most obvious choice for us. My ________ is an ambitious student, and in your college we expect to see her skills grow further, especially under the guidance of talented teachers that work in your college.\nYours truly\n__________\n__________  \nFurther Details: \nDate of Birth - __/___/____\nMobile No. - _______________ \nEmail - _______________________ \nAddress - _______________________\nHighest Qualification - ________________\nPercentage - _________________");
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        ApplicationArea.setEditable(false);
        ApplicationArea.setBackground(new java.awt.Color(0, 32, 63));
        ApplicationArea.setColumns(20);
        ApplicationArea.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        ApplicationArea.setForeground(new java.awt.Color(187, 232, 215));
        ApplicationArea.setRows(5);
        ApplicationArea.setText("To,\nThe Principal,\nXYZ COLLEGE, Meerut\n\n\tSubject: Request to enroll for admission in ________ session 20__-20__\n\nDear Sir/madam,\nThis is __________ and it is my humble request to kindly admit my ______ _________ in\n______ of your institution.\n\nI am pleased to inform you about the overall impressive academic performance\nof my child until now. After research, I found your college is undoubtedly the\nbest in your neighbourhood and therefore it is the most obvious choice for us.\nMy ________ is an ambitious student, and in your college we expect to see\nher skills grow further, especially under the guidance of talented teachers\nthat work in your college.\n\nYours truly\n__________\nDate : __________  \n\n\nFurther Details: \n\nDate of Birth - __/___/____\nMobile No. - _______________ \nAddress - _______________________\nHighest Qualification - ________________\nPercentage - _________________");
        ApplicationArea.setMargin(new java.awt.Insets(5, 5, 2, 2));
        jScrollPane1.setViewportView(ApplicationArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 510, 500);

        EditButton.setBackground(new java.awt.Color(0, 32, 63));
        EditButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EditButton.setForeground(new java.awt.Color(187, 232, 215));
        EditButton.setText("EDIT");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditButton);
        EditButton.setBounds(250, 630, 100, 40);

        SubmitButton.setBackground(new java.awt.Color(0, 32, 63));
        SubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(187, 232, 215));
        SubmitButton.setText("SUBMIT");
        SubmitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton);
        SubmitButton.setBounds(100, 630, 100, 40);

        BackButton.setBackground(new java.awt.Color(0, 32, 63));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(187, 232, 215));
        BackButton.setText("BACK");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(400, 630, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        UserID.flag = true;
        dispose();
        new StudentRequestForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
        new StudentLogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String query = "INSERT INTO `student_application`(`password`, `name`, `father_name`, `mobile_number`, `email`, `address`, `gender`, `dob`, `course`, `highest_qualification`, `percentage`, `session_start`, `session_end`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            Connection connection;
            PreparedStatement preparedStatement;
            ResultSet rs;
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar", "root", "");
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, UserID.temp[0]);
                preparedStatement.setString(2, UserID.temp[1]);
                preparedStatement.setString(3, UserID.temp[2]);
                preparedStatement.setString(4, UserID.temp[3]);
                preparedStatement.setString(5, UserID.temp[4]);
                preparedStatement.setString(6, UserID.temp[5]);
                preparedStatement.setString(7, UserID.temp[6]);
                preparedStatement.setString(8, UserID.temp[7]);
                preparedStatement.setString(9, UserID.temp[8]);
                preparedStatement.setString(10, UserID.temp[9]);
                preparedStatement.setInt(11, Integer.parseInt(UserID.temp[10]));
                preparedStatement.setString(12,Integer.toString(year));
                preparedStatement.setString(13,Integer.toString(year + 3));
                int len=0;
                len = preparedStatement.executeUpdate();
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("SELECT `application_number` FROM `student_application`");
                while(rs.next());
                rs.previous();
                int ApplicationNo =Integer.parseInt(rs.getString("application_number"));
                if (len > 0) {
                    JOptionPane.showMessageDialog(null, "Application sent Successfully !\n Application Number - "+ApplicationNo);
                }
                connection.close();
                preparedStatement.close();
                dispose();
                new StudentLogin().setVisible(true);
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }// TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ApplicationArea;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
