/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topscholars;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author K1LL3R
 */
public class StudentViewResult extends javax.swing.JFrame {

    /**
     * Creates new form ViewMarks
     */
    public StudentViewResult() {
        initComponents();
            try{
                Connection connection;
                ResultSet rs;
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/topscholar","root","");
                Statement statement = connection.createStatement();
                rs = statement.executeQuery("SELECT `subject1`, `subject2`, `subject3`, `subject4`, `subject5`, `subject6` FROM `result` WHERE `student_id`="+UserID.UserID);
                    rs.next();
                    SubjectLabel1.setText(rs.getString("subject1"));
                    SubjectLabel2.setText(rs.getString("subject2"));
                    SubjectLabel3.setText(rs.getString("subject3"));
                    SubjectLabel4.setText(rs.getString("subject4"));
                    SubjectLabel5.setText(rs.getString("subject5"));
                    SubjectLabel6.setText(rs.getString("subject6"));
                    TotalLabel.setText(Integer.toString(Integer.parseInt(SubjectLabel1.getText().trim())+Integer.parseInt(SubjectLabel2.getText().trim())+Integer.parseInt(SubjectLabel3.getText().trim())+Integer.parseInt(SubjectLabel4.getText().trim())+Integer.parseInt(SubjectLabel5.getText().trim())+Integer.parseInt(SubjectLabel6.getText().trim())));
                    PercentageLabel.setText(Integer.toString(Integer.parseInt(TotalLabel.getText().trim())/6));
                    if("BCA".equals(UserID.Course)){
                        Subject1Label.setText("MATHEMATICS :");
                        Subject2Label.setText("C PROGRAMMING :");
                        Subject3Label.setText("NETWORKING :");
                        Subject4Label.setText("DATABASE :");
                        Subject5Label.setText("STATSTICS :");
                        Subject6Label.setText("PRACTICAL :");
                    }
                
                rs.close();
                connection.close();
                statement.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Subject1Label = new javax.swing.JLabel();
        Subject2Label = new javax.swing.JLabel();
        Subject3Label = new javax.swing.JLabel();
        Subject4Label = new javax.swing.JLabel();
        Subject5Label = new javax.swing.JLabel();
        Subject6Label = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        SubjectLabel6 = new javax.swing.JLabel();
        PercentageLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        SubjectLabel1 = new javax.swing.JLabel();
        SubjectLabel2 = new javax.swing.JLabel();
        SubjectLabel3 = new javax.swing.JLabel();
        SubjectLabel4 = new javax.swing.JLabel();
        SubjectLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(363, 144));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topscholars/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 0, 110, 90);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(187, 232, 215));
        jLabel2.setText("ACADEMIC SCORE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 30, 330, 50);

        jButton1.setBackground(new java.awt.Color(0, 32, 63));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(187, 232, 215));
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 232, 215), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 490, 130, 40);

        Subject1Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject1Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject1Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject1Label.setText("Subject Name :");
        jPanel1.add(Subject1Label);
        Subject1Label.setBounds(70, 100, 150, 30);

        Subject2Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject2Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject2Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject2Label.setText("Subject Name :");
        jPanel1.add(Subject2Label);
        Subject2Label.setBounds(70, 140, 150, 30);

        Subject3Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject3Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject3Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject3Label.setText("Subject Name :");
        jPanel1.add(Subject3Label);
        Subject3Label.setBounds(70, 180, 150, 30);

        Subject4Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject4Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject4Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject4Label.setText("Subject Name :");
        jPanel1.add(Subject4Label);
        Subject4Label.setBounds(70, 220, 150, 30);

        Subject5Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject5Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject5Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject5Label.setText("Subject Name :");
        jPanel1.add(Subject5Label);
        Subject5Label.setBounds(70, 260, 150, 30);

        Subject6Label.setBackground(new java.awt.Color(0, 32, 63));
        Subject6Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Subject6Label.setForeground(new java.awt.Color(187, 232, 215));
        Subject6Label.setText("Subject Name :");
        jPanel1.add(Subject6Label);
        Subject6Label.setBounds(70, 300, 150, 30);

        jLabel25.setBackground(new java.awt.Color(0, 32, 63));
        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(187, 232, 215));
        jLabel25.setText("Total :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(70, 360, 150, 30);

        jLabel26.setBackground(new java.awt.Color(0, 32, 63));
        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(187, 232, 215));
        jLabel26.setText("Percentage :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(70, 410, 150, 30);

        SubjectLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SubjectLabel6.setForeground(new java.awt.Color(187, 232, 215));
        SubjectLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(SubjectLabel6);
        SubjectLabel6.setBounds(280, 300, 240, 30);

        PercentageLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PercentageLabel.setForeground(new java.awt.Color(187, 232, 215));
        PercentageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(PercentageLabel);
        PercentageLabel.setBounds(280, 410, 240, 30);

        TotalLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(187, 232, 215));
        TotalLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(TotalLabel);
        TotalLabel.setBounds(280, 360, 240, 30);

        SubjectLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SubjectLabel1.setForeground(new java.awt.Color(187, 232, 215));
        SubjectLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(SubjectLabel1);
        SubjectLabel1.setBounds(280, 100, 240, 30);

        SubjectLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SubjectLabel2.setForeground(new java.awt.Color(187, 232, 215));
        SubjectLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(SubjectLabel2);
        SubjectLabel2.setBounds(280, 140, 240, 30);

        SubjectLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SubjectLabel3.setForeground(new java.awt.Color(187, 232, 215));
        SubjectLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(SubjectLabel3);
        SubjectLabel3.setBounds(280, 180, 240, 30);

        SubjectLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SubjectLabel4.setForeground(new java.awt.Color(187, 232, 215));
        SubjectLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(SubjectLabel4);
        SubjectLabel4.setBounds(280, 220, 240, 30);

        SubjectLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SubjectLabel5.setForeground(new java.awt.Color(187, 232, 215));
        SubjectLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 232, 215), 3, true));
        jPanel1.add(SubjectLabel5);
        SubjectLabel5.setBounds(280, 260, 240, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new StudentMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentViewResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PercentageLabel;
    private javax.swing.JLabel Subject1Label;
    private javax.swing.JLabel Subject2Label;
    private javax.swing.JLabel Subject3Label;
    private javax.swing.JLabel Subject4Label;
    private javax.swing.JLabel Subject5Label;
    private javax.swing.JLabel Subject6Label;
    private javax.swing.JLabel SubjectLabel1;
    private javax.swing.JLabel SubjectLabel2;
    private javax.swing.JLabel SubjectLabel3;
    private javax.swing.JLabel SubjectLabel4;
    private javax.swing.JLabel SubjectLabel5;
    private javax.swing.JLabel SubjectLabel6;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
